version: '3.8'
services:

  app:
    container_name: springboot
    image: springboot
    build: ./
    ports:
      - "5555:5555"

    depends_on:
      - postgresql


  postgresql:
    image: postgres:14.1-alpine
    ports:
      - '5432:5443'
    build: ./
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_qnb

